"""Generate Cursor / IntelliJ (Junie) / OpenAI Codex integrations from the
canonical Claude Code skills + commands.

praxis ships its six SDLC expert personas and slash commands as Claude Code
native artifacts (.claude/skills, .claude/commands). Other agentic IDEs read
different files in different places. This generator is the single build step
that re-expresses the SAME source of truth in each tool's native format, so the
ported integrations never drift from the skills.

Outputs (all under integrations/<tool>/, copy into a consuming repo):

  cursor/    .cursor/rules/*.mdc  + .cursor/commands/*.md
  codex/     .praxis/*.md  + prompts/*.md  + AGENTS.praxis.md
  intellij/  .junie/guidelines.md + .junie/praxis/*.md + prompts/*.md

Deterministic: no LLM. Re-run after editing any skill or command.

Usage:
    python integrations/scripts/build_integrations.py            # write
    python integrations/scripts/build_integrations.py --check    # CI: fail if stale

Exit codes:
    0: wrote the integrations, or --check found them up to date
    1: --check found them stale (regenerate and commit)
    2: IO / arguments error
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parent
INTEGRATIONS_DIR = SCRIPTS_DIR.parent
REPO_ROOT = INTEGRATIONS_DIR.parent
CLAUDE_DIR = REPO_ROOT / ".claude"
SKILLS_DIR = CLAUDE_DIR / "skills"
COMMANDS_DIR = CLAUDE_DIR / "commands"

sys.path.insert(0, str(CLAUDE_DIR / "factory" / "validators"))
from validate_frontmatter import _read_frontmatter  # noqa: E402

# skill folder -> persona display title
EXPERTS: dict[str, str] = {
    "business-analyst": "Business Analyst",
    "product-owner": "Product Owner",
    "software-architect": "Software Architect",
    "developer": "Developer",
    "qa-engineer": "QA Engineer",
    "devops-engineer": "DevOps Engineer",
    "security-engineer": "Security Engineer",
    "cybersecurity-architect": "Cybersecurity Architect",
    "ux-ui-engineer": "UX/UI Engineer",
    "frontend-architect": "Frontend Architect",
    "frontend-engineer": "Frontend Engineer",
    "data-engineer": "Data Engineer",
    "ml-ai-engineer": "ML/AI Engineer",
}

# single-persona command -> skill folder
COMMAND_PERSONA: dict[str, str] = {
    "analyst": "business-analyst",
    "product": "product-owner",
    "architect": "software-architect",
    "developer": "developer",
    "qa": "qa-engineer",
    "devops": "devops-engineer",
    "security": "security-engineer",
    "security-architect": "cybersecurity-architect",
    "ux": "ux-ui-engineer",
    "frontend-architect": "frontend-architect",
    "frontend": "frontend-engineer",
    "data": "data-engineer",
    "ml": "ml-ai-engineer",
}

# multi-persona workflows (no single owning skill)
ORCHESTRATION = ("new-feature", "review-changes")

# factory-internal, repo-specific — not portable to consuming projects
SKIP_COMMANDS = {"validate-skills"}

# matches `<skill-name>` written as an inline code token (exact known names only)
_SKILL_TOKEN_RE = re.compile(r"`(" + "|".join(map(re.escape, EXPERTS)) + r")`")

BANNER = (
    "<!-- Generated by integrations/scripts/build_integrations.py from "
    ".claude/skills + .claude/commands. Do not edit by hand; run "
    "`make integrations`. -->"
)


# --------------------------------------------------------------------------- #
# Source readers
# --------------------------------------------------------------------------- #
def _body(md_path: Path) -> str:
    """Return the markdown body of a file, stripped of YAML frontmatter."""
    text = md_path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if lines and lines[0].strip() == "---":
        for idx in range(1, len(lines)):
            if lines[idx].strip() == "---":
                return "\n".join(lines[idx + 1 :]).strip("\n")
    return text.strip("\n")


def _persona_guide(skill: str) -> str:
    """Bundle a skill's SKILL.md body + practices + checklist into one
    self-contained persona guide (no skill loader required)."""
    sdir = SKILLS_DIR / skill
    body = _body(sdir / "SKILL.md")
    practices = (sdir / "references" / "practices.md").read_text(encoding="utf-8").strip("\n")
    checklist = (sdir / "references" / "checklist.md").read_text(encoding="utf-8").strip("\n")
    return f"{BANNER}\n\n{body}\n\n---\n\n{practices}\n\n---\n\n{checklist}\n"


def _skill_description(skill: str) -> str:
    fm, _ = _read_frontmatter(SKILLS_DIR / skill / "SKILL.md")
    return " ".join(str(fm.get("description") or "").split())


# --------------------------------------------------------------------------- #
# Command porting — rewrite Claude "skill" references into self-contained,
# tool-native references to the bundled persona guides.
# --------------------------------------------------------------------------- #
def _port_command(name: str, *, tool: str, persona_ref, personas_label: str) -> str:
    """Return a portable command/prompt body for `name`.

    persona_ref(skill)   -> how to point at one persona guide in this tool
    personas_label       -> how to point at the whole persona set in this tool
    """
    body = _body(COMMANDS_DIR / f"{name}.md")

    if name in COMMAND_PERSONA:
        skill = COMMAND_PERSONA[name]
        title = EXPERTS[skill]
        ref = persona_ref(skill)
        # "Use the **software-architect** skill and answer as ..." (role tail kept)
        body = re.sub(
            r"Use the \*\*[a-z-]+\*\* skill and answer as",
            f"Adopt the {title} persona guide ({ref}) and answer as",
            body,
        )
        body = body.replace(
            "Draw on the skill's `references/practices.md` and "
            "`references/checklist.md` as needed.",
            f"Draw on the {title} persona guide ({ref}) as needed.",
        )
    else:
        # orchestration workflows: many personas, point at the set
        body = body.replace(
            "Orchestrate the six SDLC expert skills",
            "Orchestrate the six SDLC expert personas",
        )
        # `/new-feature` runs each phase in a Claude Code subagent; other tools
        # have no subagents, so collapse the whole "## Execution" block into a
        # single-thread instruction that points at the bundled persona guides.
        body = re.sub(
            r"## Execution\n.*?(?=\n## Checkpoint)",
            "## Execution\n\n"
            "Work through the phases in order in **one conversation** — do not "
            "spawn subagents; keep context flowing so each phase sees the prior "
            f"artifacts. For each phase, open the matching persona guide "
            f"({personas_label}), apply its practices, self-check against its "
            "checklist, and produce the listed artifact. After the Architect "
            "phase, add any conditional domain expert the feature warrants "
            "(table above) before the QA, DevOps, and summary phases.\n",
            body,
            flags=re.DOTALL,
        )
        # the scope-gate aside about subagents is Claude-only; drop it for
        # single-thread tools.
        body = body.replace(" (subagents cannot talk to the user)", "")
        body = body.replace(
            "Pick **only** the experts the diff actually warrants (do not run all "
            "of them by reflex). Load each chosen skill and apply its "
            "`references/checklist.md`:",
            "Pick **only** the experts the diff actually warrants (do not run all "
            "of them by reflex). Open the matching persona guide "
            f"({personas_label}) and apply its checklist:",
        )
        # drop redundant "(`business-analyst`)" id parentheticals in lists
        body = re.sub(r" \(`[a-z-]+`\)", "", body)

    # inline `<skill>` tokens -> persona Title (safety net, exact names only)
    body = _SKILL_TOKEN_RE.sub(lambda m: EXPERTS[m.group(1)], body)
    # any stray reference-file mentions
    body = body.replace("`references/checklist.md`", "the persona checklist")
    body = body.replace("`references/practices.md`", "the persona practices")

    if tool != "codex":
        # Cursor / IntelliJ have no $ARGUMENTS substitution; the user types after.
        body = body.replace("`$ARGUMENTS`", "the scope you give it")
        body = body.replace(
            "$ARGUMENTS", "*(describe your request when you run this command)*"
        )

    return body.strip() + "\n"


# --------------------------------------------------------------------------- #
# Roster (shared by every doctrine bridge)
# --------------------------------------------------------------------------- #
def _roster_table() -> str:
    rows = ["| Persona | Consult when… |", "| ------- | ------------- |"]
    for skill, title in EXPERTS.items():
        desc = _skill_description(skill)
        use = desc.split("Use when", 1)[-1].strip(" .:").strip()
        for prefix in ("the user asks to ", "the user asks about ", "the user asks ", "the user "):
            if use.startswith(prefix):
                use = use[len(prefix) :]
                break
        use = use or desc
        use = use[0].upper() + use[1:]
        if len(use) > 180:
            use = use[:179].rstrip() + "…"
        rows.append(f"| **{title}** | {use} |")
    return "\n".join(rows)


# --------------------------------------------------------------------------- #
# Per-tool builders -> {relative path under integrations/: content}
# --------------------------------------------------------------------------- #
def _cursor() -> dict[str, str]:
    out: dict[str, str] = {}
    ref = lambda skill: f"the `praxis-{skill}` rule"  # noqa: E731
    personas_label = "the `praxis-*` rules"

    # always-applied doctrine bridge
    out["cursor/.cursor/rules/praxis.mdc"] = (
        "---\n"
        "description: praxis SDLC experts — personas (Business Analyst, "
        "Product Owner, Software Architect, Developer, QA, DevOps, Security "
        "Engineer, Cybersecurity Architect, UX/UI Engineer, Frontend Architect, "
        "Frontend Engineer) plus the review and new-feature workflows. Reach for "
        "the matching praxis-* rule when a task fits a role.\n"
        "alwaysApply: true\n"
        "---\n\n"
        f"{BANNER}\n\n"
        "# praxis — SDLC expert personas\n\n"
        "This project carries the praxis SDLC experts. Read `AGENTS.md` for repo "
        "doctrine. When a task fits one of the roles below, adopt that persona; "
        "its full practices and checklist live in the matching `praxis-<role>` "
        "rule (auto-attached when relevant) and you can also invoke it explicitly "
        "with the matching command under `.cursor/commands/`.\n\n"
        f"{_roster_table()}\n\n"
        "`/new-feature` runs the core six (BA → PO → Architect → Developer → QA "
        "→ DevOps) in lifecycle order; `/review-changes` routes the current diff "
        "to the relevant personas (including the security experts) with "
        "severity-tagged findings.\n"
    )

    # persona rules (Agent Requested: description-gated auto-attach)
    for skill, title in EXPERTS.items():
        out[f"cursor/.cursor/rules/praxis-{skill}.mdc"] = (
            "---\n"
            f"description: {_skill_description(skill)}\n"
            "---\n\n" + _persona_guide(skill)
        )

    # slash commands
    for name in list(COMMAND_PERSONA) + list(ORCHESTRATION):
        out[f"cursor/.cursor/commands/{name}.md"] = (
            f"{BANNER}\n\n"
            + _port_command(name, tool="cursor", persona_ref=ref, personas_label=personas_label)
        )

    out["cursor/README.md"] = _cursor_readme()
    return out


def _codex() -> dict[str, str]:
    out: dict[str, str] = {}
    ref = lambda skill: f"`.praxis/{skill}.md`"  # noqa: E731
    personas_label = "in `.praxis/`"

    # persona guides shipped in-repo so Codex can open them on demand
    for skill in EXPERTS:
        out[f"codex/.praxis/{skill}.md"] = _persona_guide(skill)

    # roster snippet to merge into the consuming repo's AGENTS.md
    out["codex/AGENTS.praxis.md"] = (
        f"{BANNER}\n\n"
        "# praxis SDLC experts\n\n"
        "This repo carries the praxis SDLC expert personas under `.praxis/`. When "
        "a task fits one of the roles below, open the matching `.praxis/<role>.md` "
        "guide and adopt that persona.\n\n"
        f"{_roster_table()}\n\n"
        "Reusable slash commands for each persona live in `~/.codex/prompts/` "
        "(install them with the prompts in this integration); invoke e.g. "
        "`/praxis-architect`, `/praxis-review-changes`.\n"
    )

    # prompts for ~/.codex/prompts/ (namespaced; $ARGUMENTS kept)
    for name in list(COMMAND_PERSONA) + list(ORCHESTRATION):
        out[f"codex/prompts/praxis-{name}.md"] = (
            f"{BANNER}\n\n"
            + _port_command(name, tool="codex", persona_ref=ref, personas_label=personas_label)
        )

    out["codex/README.md"] = _codex_readme()
    return out


def _intellij() -> dict[str, str]:
    out: dict[str, str] = {}
    ref = lambda skill: f"`.junie/praxis/{skill}.md`"  # noqa: E731
    personas_label = "in `.junie/praxis/`"

    # Junie guidelines = doctrine bridge + persona index
    index = "\n".join(
        f"- **{title}** — `.junie/praxis/{skill}.md`" for skill, title in EXPERTS.items()
    )
    out["intellij/.junie/guidelines.md"] = (
        f"{BANNER}\n\n"
        "# Project guidelines — praxis SDLC experts\n\n"
        "Read `AGENTS.md` for full repo doctrine (JetBrains AI Assistant reads it "
        "natively). This project carries the praxis SDLC expert personas. When a "
        "task fits one of the roles below, open its guide under `.junie/praxis/` "
        "and adopt that persona.\n\n"
        f"{_roster_table()}\n\n"
        "## Persona guides\n\n"
        f"{index}\n\n"
        "Ready-made prompts for each persona and for the new-feature / "
        "review-changes workflows live in `prompts/` — save them to the AI "
        "Assistant prompt library.\n"
    )

    for skill in EXPERTS:
        out[f"intellij/.junie/praxis/{skill}.md"] = _persona_guide(skill)

    for name in list(COMMAND_PERSONA) + list(ORCHESTRATION):
        out[f"intellij/prompts/{name}.md"] = (
            f"{BANNER}\n\n"
            + _port_command(name, tool="intellij", persona_ref=ref, personas_label=personas_label)
        )

    out["intellij/README.md"] = _intellij_readme()
    return out


# --------------------------------------------------------------------------- #
# Per-tool READMEs
# --------------------------------------------------------------------------- #
def _cursor_readme() -> str:
    return (
        f"{BANNER}\n\n"
        "# praxis for Cursor\n\n"
        "The praxis SDLC experts and their workflows, re-expressed as Cursor "
        "**project rules** and **commands**.\n\n"
        "## Install\n\n"
        "Copy the `.cursor/` directory into your project root (merge if you "
        "already have one):\n\n"
        "```bash\n"
        "cp -R integrations/cursor/.cursor <your-repo>/\n"
        "cp AGENTS.md <your-repo>/      # optional: Cursor reads AGENTS.md natively\n"
        "```\n\n"
        "## Use\n\n"
        "- **Personas auto-attach.** Each expert is a description-gated rule "
        "(`praxis-business-analyst`, …); Cursor pulls in the relevant one when "
        "your request matches it. `praxis.mdc` is always applied and tells the "
        "agent when to reach for each persona.\n"
        "- **Invoke explicitly** with a command: `/architect`, `/developer`, "
        "`/qa`, `/analyst`, `/product`, `/devops`, `/security`, "
        "`/security-architect`, `/ux`, `/frontend-architect`, `/frontend`.\n"
        "- **Workflows:** `/new-feature` runs the core six in order; "
        "`/review-changes` reviews the current diff.\n"
    )


def _codex_readme() -> str:
    return (
        f"{BANNER}\n\n"
        "# praxis for OpenAI Codex\n\n"
        "The praxis SDLC experts and their workflows, re-expressed for Codex "
        "(`AGENTS.md` + in-repo persona guides + `~/.codex/prompts`).\n\n"
        "## Install\n\n"
        "1. Codex reads `AGENTS.md` natively. Append `AGENTS.praxis.md` to your "
        "repo's `AGENTS.md` (or copy praxis's `AGENTS.md`).\n"
        "2. Ship the persona guides with your code:\n\n"
        "```bash\n"
        "cp -R integrations/codex/.praxis <your-repo>/\n"
        "```\n\n"
        "3. Install the slash commands into your Codex prompts dir:\n\n"
        "```bash\n"
        "cp integrations/codex/prompts/*.md ~/.codex/prompts/\n"
        "```\n\n"
        "## Use\n\n"
        "- Type `/praxis-architect`, `/praxis-developer`, `/praxis-qa`, "
        "`/praxis-analyst`, `/praxis-product`, `/praxis-devops`, "
        "`/praxis-security`, `/praxis-security-architect`, `/praxis-ux`, "
        "`/praxis-frontend-architect`, `/praxis-frontend`. Each adopts the "
        "persona from `.praxis/<role>.md` and uses `$ARGUMENTS` as the request.\n"
        "- Workflows: `/praxis-new-feature`, `/praxis-review-changes`.\n"
    )


def _intellij_readme() -> str:
    return (
        f"{BANNER}\n\n"
        "# praxis for IntelliJ (JetBrains AI Assistant & Junie)\n\n"
        "The praxis SDLC experts and their workflows, re-expressed as Junie "
        "guidelines + persona guides + reusable prompts.\n\n"
        "## Install\n\n"
        "Copy the `.junie/` directory into your project root:\n\n"
        "```bash\n"
        "cp -R integrations/intellij/.junie <your-repo>/\n"
        "cp AGENTS.md <your-repo>/      # JetBrains AI Assistant reads AGENTS.md natively\n"
        "```\n\n"
        "Junie reads `.junie/guidelines.md`; the persona guides it references live "
        "in `.junie/praxis/`.\n\n"
        "## Use\n\n"
        "- Ask Junie or the AI Assistant to *act as the praxis Software Architect* "
        "(or any role) — it follows `guidelines.md` and the matching persona "
        "guide.\n"
        "- IntelliJ has no repo-level slash commands, so the files in `prompts/` "
        "are **ready-to-paste prompt snippets** (one per persona, plus the "
        "new-feature and review-changes workflows). Save them to the AI Assistant "
        "prompt library for one-click reuse.\n"
    )


# --------------------------------------------------------------------------- #
# Driver
# --------------------------------------------------------------------------- #
TOOL_DIRS = ("cursor", "codex", "intellij")


def build_all() -> dict[str, str]:
    out: dict[str, str] = {}
    out.update(_cursor())
    out.update(_codex())
    out.update(_intellij())
    return out


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate Cursor / IntelliJ / Codex integrations from the Claude skills."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if any generated file is missing or stale (do not write).",
    )
    args = parser.parse_args()

    files = build_all()

    if args.check:
        stale: list[str] = []
        for rel, content in files.items():
            path = INTEGRATIONS_DIR / rel
            existing = path.read_text(encoding="utf-8") if path.is_file() else None
            if existing != content:
                stale.append(rel)
        # detect orphan files under the generated tool dirs
        expected = {(INTEGRATIONS_DIR / rel).resolve() for rel in files}
        for tool in TOOL_DIRS:
            base = INTEGRATIONS_DIR / tool
            if base.is_dir():
                for path in base.rglob("*"):
                    if path.is_file() and path.resolve() not in expected:
                        stale.append(str(path.relative_to(INTEGRATIONS_DIR)) + " (orphan)")
        if stale:
            print("Integrations are stale. Run `make integrations` and commit:", file=sys.stderr)
            for rel in sorted(stale):
                print(f"  - {rel}", file=sys.stderr)
            return 1
        print(f"Integrations up to date ({len(files)} files).")
        return 0

    # write mode: own the three tool dirs entirely
    import shutil

    for tool in TOOL_DIRS:
        base = INTEGRATIONS_DIR / tool
        if base.exists():
            shutil.rmtree(base)
    for rel, content in files.items():
        path = INTEGRATIONS_DIR / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    print(f"Wrote {len(files)} files across {', '.join(TOOL_DIRS)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
